name: dev on push

on:
  push:
    branches:
      - dev

jobs:
  check-source-branch:
    name: Check source branch syntax
    runs-on: ubuntu-latest
    steps:
      - name: "Use github actions. "
        uses: actions/checkout@v2
      - name: "Check source branch syntax is OK"
        run: |
          echo "dev on push -> ${{ github.event_name }}, ${{ github.action }}, ${{ github.head_ref }} "
          exit 0
