name: dev on push

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  check-source-branch:
    name: Check source branch syntax
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: "Use github actions. "
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
