name: release on pull request

on:
  pull_request:
    types: [closed]
    branches:
      - release

jobs:
  check-source-branch:
    name: Check source branch syntax
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: "Use github actions. "
        uses: actions/checkout@v2
      - name: "Check source branch syntax is OK"
        run: |
          echo "dev on push -> ${{ github.event.pull_request.merged }} ${{ github.event.pull_request.head.ref }} ${{ github.event_name }}, ${{ github.action }}, ${{ github.head_ref }}, ${{ github.base_ref }}"
          exit 0